<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Assessment;
use App\Models\CrisisResource;
use App\Models\Resource;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        User::factory()->create(['name' => 'Test User', 'email' => 'test@example.com']);

        $this->seedAssessments();
        $this->seedCrisisResources();
        $this->seedResources();
    }

    private function seedAssessments()
    {
        $standardOptions = [
            ['label' => 'Not at all', 'score' => 0],
            ['label' => 'Several days', 'score' => 1],
            ['label' => 'More than half the days', 'score' => 2],
            ['label' => 'Nearly every day', 'score' => 3],
        ];

        // ── PHQ-9 ──
        $a = Assessment::create(['title'=>'PHQ-9 Depression Screen','description'=>'A 9-item questionnaire to assess the severity of depression.','type'=>'phq9','icon'=>'🌧️','color'=>'indigo','estimated_minutes'=>5,'category'=>'Depression','question_count'=>9]);
        foreach(['Little interest or pleasure in doing things','Feeling down, depressed, or hopeless','Trouble falling or staying asleep, or sleeping too much','Feeling tired or having little energy','Poor appetite or overeating','Feeling bad about yourself — or that you are a failure','Trouble concentrating on things','Moving or speaking so slowly that other people could have noticed, or being fidgety or restless','Thoughts that you would be better off dead or of hurting yourself'] as $i=>$q)
            $a->questions()->create(['text'=>"Over the last 2 weeks, how often have you been bothered by: {$q}?",'order'=>$i+1,'options'=>$standardOptions]);
        foreach([['min_score'=>0,'max_score'=>4,'interpretation'=>'Minimal depression','recommendation'=>'Your score suggests minimal depression. Maintain healthy habits like regular exercise, good sleep, and social connections.'],['min_score'=>5,'max_score'=>9,'interpretation'=>'Mild depression','recommendation'=>'Your score suggests mild depression. Consider monitoring your symptoms, maintaining a routine, and practicing self-care.'],['min_score'=>10,'max_score'=>14,'interpretation'=>'Moderate depression','recommendation'=>'Your score suggests moderate depression. Please consider consulting a healthcare professional or counselor.'],['min_score'=>15,'max_score'=>19,'interpretation'=>'Moderately severe depression','recommendation'=>'Your score suggests moderately severe depression. It is highly recommended that you seek guidance from a mental health professional.'],['min_score'=>20,'max_score'=>27,'interpretation'=>'Severe depression','recommendation'=>'Your score suggests severe depression. Please contact a healthcare provider or crisis hotline immediately.']] as $r)
            $a->guidanceRules()->create($r);

        // ── GAD-7 ──
        $a = Assessment::create(['title'=>'GAD-7 Anxiety Screen','description'=>'A 7-item questionnaire for screening generalized anxiety disorder.','type'=>'gad7','icon'=>'🍃','color'=>'teal','estimated_minutes'=>4,'category'=>'Anxiety','question_count'=>7]);
        foreach(['Feeling nervous, anxious, or on edge','Not being able to stop or control worrying','Worrying too much about different things','Trouble relaxing','Being so restless that it is hard to sit still','Becoming easily annoyed or irritable','Feeling afraid, as if something awful might happen'] as $i=>$q)
            $a->questions()->create(['text'=>"Over the last 2 weeks, how often have you been bothered by: {$q}?",'order'=>$i+1,'options'=>$standardOptions]);
        foreach([['min_score'=>0,'max_score'=>4,'interpretation'=>'Minimal anxiety','recommendation'=>'Your score suggests minimal anxiety. Continue with healthy coping strategies.'],['min_score'=>5,'max_score'=>9,'interpretation'=>'Mild anxiety','recommendation'=>'Your score suggests mild anxiety. Practice relaxation techniques and monitor your stress levels.'],['min_score'=>10,'max_score'=>14,'interpretation'=>'Moderate anxiety','recommendation'=>'Your score suggests moderate anxiety. Consider speaking with a healthcare professional.'],['min_score'=>15,'max_score'=>21,'interpretation'=>'Severe anxiety','recommendation'=>'Your score suggests severe anxiety. Please seek help from a mental health specialist.']] as $r)
            $a->guidanceRules()->create($r);

        // ── PSS (Perceived Stress Scale - 10 items) ──
        $pssOptions = [['label'=>'Never','score'=>0],['label'=>'Almost Never','score'=>1],['label'=>'Sometimes','score'=>2],['label'=>'Fairly Often','score'=>3],['label'=>'Very Often','score'=>4]];
        $a = Assessment::create(['title'=>'PSS Stress Scale','description'=>'A 10-item scale measuring the perception of stress over the past month.','type'=>'pss','icon'=>'🔥','color'=>'amber','estimated_minutes'=>5,'category'=>'Stress','question_count'=>10]);
        foreach(['Been upset because of something that happened unexpectedly','Felt unable to control the important things in your life','Felt nervous and stressed','Felt confident about your ability to handle personal problems','Felt that things were going your way','Found that you could not cope with all the things you had to do','Been able to control irritations in your life','Felt that you were on top of things','Been angered because of things outside your control','Felt difficulties were piling up so high you could not overcome them'] as $i=>$q)
            $a->questions()->create(['text'=>"In the last month, how often have you: {$q}?",'order'=>$i+1,'options'=>$pssOptions]);
        foreach([['min_score'=>0,'max_score'=>13,'interpretation'=>'Low stress','recommendation'=>'Your stress levels appear low. Keep up your current coping strategies!'],['min_score'=>14,'max_score'=>26,'interpretation'=>'Moderate stress','recommendation'=>'You are experiencing moderate stress. Consider time management techniques and relaxation exercises.'],['min_score'=>27,'max_score'=>40,'interpretation'=>'High stress','recommendation'=>'Your stress levels are high. Please consider seeking professional support and implementing stress reduction strategies.']] as $r)
            $a->guidanceRules()->create($r);

        // ── WHO-5 Wellbeing Index ──
        $who5Options = [['label'=>'All of the time','score'=>5],['label'=>'Most of the time','score'=>4],['label'=>'More than half the time','score'=>3],['label'=>'Less than half the time','score'=>2],['label'=>'Some of the time','score'=>1],['label'=>'At no time','score'=>0]];
        $a = Assessment::create(['title'=>'WHO-5 Wellbeing Index','description'=>'A short questionnaire measuring current mental well-being.','type'=>'who5','icon'=>'🌟','color'=>'sage','estimated_minutes'=>2,'category'=>'Wellbeing','question_count'=>5]);
        foreach(['I have felt cheerful and in good spirits','I have felt calm and relaxed','I have felt active and vigorous','I woke up feeling fresh and rested','My daily life has been filled with things that interest me'] as $i=>$q)
            $a->questions()->create(['text'=>"Over the last 2 weeks: {$q}",'order'=>$i+1,'options'=>$who5Options]);
        foreach([['min_score'=>0,'max_score'=>12,'interpretation'=>'Low wellbeing','recommendation'=>'Your wellbeing score is low. Please consider reaching out to a healthcare professional for support.'],['min_score'=>13,'max_score'=>18,'interpretation'=>'Moderate wellbeing','recommendation'=>'Your wellbeing is moderate. Focus on activities that bring you joy and connection.'],['min_score'=>19,'max_score'=>25,'interpretation'=>'Good wellbeing','recommendation'=>'Great! Your wellbeing score is good. Continue your positive habits!']] as $r)
            $a->guidanceRules()->create($r);

        // ── ISI (Insomnia Severity Index) ──
        $isiOptions = [['label'=>'None','score'=>0],['label'=>'Mild','score'=>1],['label'=>'Moderate','score'=>2],['label'=>'Severe','score'=>3],['label'=>'Very Severe','score'=>4]];
        $a = Assessment::create(['title'=>'ISI Insomnia Index','description'=>'A 7-item measure of insomnia severity and sleep quality.','type'=>'isi','icon'=>'🌙','color'=>'purple','estimated_minutes'=>3,'category'=>'Sleep','question_count'=>7]);
        foreach(['Difficulty falling asleep','Difficulty staying asleep','Problems waking up too early','How satisfied are you with your current sleep pattern','How noticeable to others do you think your sleep problem is','How worried/distressed are you about your current sleep problem','How much does your sleep problem interfere with daily functioning'] as $i=>$q)
            $a->questions()->create(['text'=>"Please rate the current severity of: {$q}",'order'=>$i+1,'options'=>$isiOptions]);
        foreach([['min_score'=>0,'max_score'=>7,'interpretation'=>'No clinically significant insomnia','recommendation'=>'Your sleep appears healthy. Maintain good sleep hygiene!'],['min_score'=>8,'max_score'=>14,'interpretation'=>'Subthreshold insomnia','recommendation'=>'You may have mild sleep difficulties. Consider improving your sleep routine.'],['min_score'=>15,'max_score'=>21,'interpretation'=>'Clinical insomnia (moderate)','recommendation'=>'You may be experiencing moderate insomnia. Consider consulting a sleep specialist.'],['min_score'=>22,'max_score'=>28,'interpretation'=>'Clinical insomnia (severe)','recommendation'=>'Your insomnia symptoms are severe. Please seek professional help.']] as $r)
            $a->guidanceRules()->create($r);

        // ── ASRS (ADHD Screening) ──
        $a = Assessment::create(['title'=>'ASRS ADHD Screen','description'=>'A 6-item screening tool for adult ADHD symptoms.','type'=>'asrs','icon'=>'⚡','color'=>'orange','estimated_minutes'=>3,'category'=>'ADHD','question_count'=>6]);
        foreach(['How often do you have trouble wrapping up final details of a project','How often do you have difficulty getting things in order for a task','How often do you have problems remembering appointments or obligations','How often do you avoid starting a task that requires a lot of thought','How often do you fidget or squirm when you have to sit down for a long time','How often do you feel overly active and compelled to do things'] as $i=>$q)
            $a->questions()->create(['text'=>"{$q}?",'order'=>$i+1,'options'=>[['label'=>'Never','score'=>0],['label'=>'Rarely','score'=>1],['label'=>'Sometimes','score'=>2],['label'=>'Often','score'=>3],['label'=>'Very Often','score'=>4]]]);
        foreach([['min_score'=>0,'max_score'=>9,'interpretation'=>'Low likelihood of ADHD','recommendation'=>'Your score is in the normal range. No further screening needed.'],['min_score'=>10,'max_score'=>16,'interpretation'=>'Possible ADHD indicators','recommendation'=>'Some ADHD indicators are present. Consider a full evaluation by a professional.'],['min_score'=>17,'max_score'=>24,'interpretation'=>'High likelihood of ADHD','recommendation'=>'Your score suggests a high likelihood of ADHD. Please consult a healthcare professional for a comprehensive evaluation.']] as $r)
            $a->guidanceRules()->create($r);

        // ── Copenhagen Burnout Inventory (simplified) ──
        $burnoutOptions = [['label'=>'Never/Almost never','score'=>0],['label'=>'Seldom','score'=>1],['label'=>'Sometimes','score'=>2],['label'=>'Often','score'=>3],['label'=>'Always','score'=>4]];
        $a = Assessment::create(['title'=>'Burnout Assessment','description'=>'A questionnaire based on the Copenhagen Burnout Inventory to assess personal burnout.','type'=>'cbi','icon'=>'🔋','color'=>'red','estimated_minutes'=>4,'category'=>'Burnout','question_count'=>6]);
        foreach(['How often do you feel tired','How often are you physically exhausted','How often are you emotionally exhausted','How often do you think "I can\'t take it anymore"','How often do you feel worn out','How often do you feel weak and susceptible to illness'] as $i=>$q)
            $a->questions()->create(['text'=>"{$q}?",'order'=>$i+1,'options'=>$burnoutOptions]);
        foreach([['min_score'=>0,'max_score'=>7,'interpretation'=>'Low burnout','recommendation'=>'Your burnout levels are low. Keep maintaining work-life balance!'],['min_score'=>8,'max_score'=>15,'interpretation'=>'Moderate burnout','recommendation'=>'You show signs of moderate burnout. Take breaks, set boundaries, and prioritize self-care.'],['min_score'=>16,'max_score'=>24,'interpretation'=>'High burnout','recommendation'=>'Your burnout levels are high. Consider taking time off and consulting a professional about your work-life balance.']] as $r)
            $a->guidanceRules()->create($r);
    }

    private function seedCrisisResources()
    {
        $resources = [
            // India
            ['name'=>'Kiran Mental Health Helpline','phone'=>'1800-599-0019','country'=>'India','country_code'=>'IN','type'=>'helpline','description'=>'24/7 toll-free helpline by Ministry of Health & Family Welfare.','url'=>'','available_hours'=>'24/7','languages'=>['English','Hindi']],
            ['name'=>'iCALL','phone'=>'+91-9152987821','country'=>'India','country_code'=>'IN','type'=>'helpline','description'=>'Psychosocial helpline by TISS.','url'=>'https://icallhelpline.org','available_hours'=>'Mon-Sat, 8am-10pm','languages'=>['English','Hindi','Marathi']],
            ['name'=>'AASRA','phone'=>'+91-9820466726','country'=>'India','country_code'=>'IN','type'=>'helpline','description'=>'Crisis intervention center for the suicidal and distressed.','url'=>'http://www.aasra.info','available_hours'=>'24/7','languages'=>['English','Hindi']],
            ['name'=>'Vandrevala Foundation','phone'=>'1860-2662-345','country'=>'India','country_code'=>'IN','type'=>'helpline','description'=>'Free, confidential, 24/7 mental health support.','url'=>'https://www.vandrevalafoundation.com','available_hours'=>'24/7','languages'=>['English','Hindi']],
            // USA
            ['name'=>'988 Suicide & Crisis Lifeline','phone'=>'988','country'=>'USA','country_code'=>'US','type'=>'helpline','description'=>'Free and confidential support for people in distress.','url'=>'https://988lifeline.org','available_hours'=>'24/7','languages'=>['English','Spanish']],
            ['name'=>'Crisis Text Line','phone'=>'Text HOME to 741741','country'=>'USA','country_code'=>'US','type'=>'text_line','description'=>'Free 24/7 crisis text line.','url'=>'https://www.crisistextline.org','available_hours'=>'24/7','languages'=>['English']],
            ['name'=>'SAMHSA National Helpline','phone'=>'1-800-662-4357','country'=>'USA','country_code'=>'US','type'=>'helpline','description'=>'Substance abuse and mental health treatment referral service.','url'=>'https://www.samhsa.gov/find-help/national-helpline','available_hours'=>'24/7','languages'=>['English','Spanish']],
            // UK
            ['name'=>'Samaritans','phone'=>'116 123','country'=>'UK','country_code'=>'GB','type'=>'helpline','description'=>'Free emotional support 24/7.','url'=>'https://www.samaritans.org','available_hours'=>'24/7','languages'=>['English']],
            ['name'=>'SHOUT','phone'=>'Text SHOUT to 85258','country'=>'UK','country_code'=>'GB','type'=>'text_line','description'=>'Free, confidential, 24/7 text support.','url'=>'https://giveusashout.org','available_hours'=>'24/7','languages'=>['English']],
            // Canada
            ['name'=>'Talk Suicide Canada','phone'=>'1-833-456-4566','country'=>'Canada','country_code'=>'CA','type'=>'helpline','description'=>'National crisis support service.','url'=>'https://talksuicide.ca','available_hours'=>'24/7','languages'=>['English','French']],
            ['name'=>'Kids Help Phone','phone'=>'1-800-668-6868','country'=>'Canada','country_code'=>'CA','type'=>'helpline','description'=>'Free counselling for young people.','url'=>'https://kidshelpphone.ca','available_hours'=>'24/7','languages'=>['English','French']],
            // Australia
            ['name'=>'Lifeline Australia','phone'=>'13 11 14','country'=>'Australia','country_code'=>'AU','type'=>'helpline','description'=>'24/7 crisis support and suicide prevention.','url'=>'https://www.lifeline.org.au','available_hours'=>'24/7','languages'=>['English']],
            ['name'=>'Beyond Blue','phone'=>'1300 22 4636','country'=>'Australia','country_code'=>'AU','type'=>'helpline','description'=>'Mental health support for anxiety and depression.','url'=>'https://www.beyondblue.org.au','available_hours'=>'24/7','languages'=>['English']],
            // Germany
            ['name'=>'Telefonseelsorge','phone'=>'0800 111 0 111','country'=>'Germany','country_code'=>'DE','type'=>'helpline','description'=>'Free, anonymous crisis counselling.','url'=>'https://www.telefonseelsorge.de','available_hours'=>'24/7','languages'=>['German']],
            // France
            ['name'=>'SOS Amitié','phone'=>'09 72 39 40 50','country'=>'France','country_code'=>'FR','type'=>'helpline','description'=>'Emotional support and suicide prevention.','url'=>'https://www.sos-amitie.com','available_hours'=>'24/7','languages'=>['French']],
            // Japan
            ['name'=>'TELL Lifeline','phone'=>'03-5774-0992','country'=>'Japan','country_code'=>'JP','type'=>'helpline','description'=>'English-language crisis support in Japan.','url'=>'https://telljp.com/lifeline','available_hours'=>'9am-11pm','languages'=>['English','Japanese']],
            // Brazil
            ['name'=>'CVV','phone'=>'188','country'=>'Brazil','country_code'=>'BR','type'=>'helpline','description'=>'Centro de Valorização da Vida — emotional support.','url'=>'https://www.cvv.org.br','available_hours'=>'24/7','languages'=>['Portuguese']],
            // South Africa
            ['name'=>'SADAG','phone'=>'0800 567 567','country'=>'South Africa','country_code'=>'ZA','type'=>'helpline','description'=>'South African Depression and Anxiety Group helpline.','url'=>'https://www.sadag.org','available_hours'=>'24/7','languages'=>['English','Afrikaans','Zulu']],
            // Nigeria
            ['name'=>'MANI Helpline','phone'=>'+234 809 111 6264','country'=>'Nigeria','country_code'=>'NG','type'=>'helpline','description'=>'Mentally Aware Nigeria Initiative support line.','url'=>'https://www.mentallyaware.org','available_hours'=>'Mon-Fri 9am-5pm','languages'=>['English']],
            // Pakistan
            ['name'=>'Umang Helpline','phone'=>'0311-7786264','country'=>'Pakistan','country_code'=>'PK','type'=>'helpline','description'=>'Mental health helpline for Pakistan.','url'=>'','available_hours'=>'9am-9pm','languages'=>['English','Urdu']],
            // Bangladesh
            ['name'=>'Kaan Pete Roi','phone'=>'+1-888-8BADHON','country'=>'Bangladesh','country_code'=>'BD','type'=>'helpline','description'=>'Bengali emotional support helpline.','url'=>'https://www.kaanpeteroi.com','available_hours'=>'Various hours','languages'=>['Bengali','English']],
            // Philippines
            ['name'=>'NCMH Crisis Hotline','phone'=>'0917-899-8727','country'=>'Philippines','country_code'=>'PH','type'=>'helpline','description'=>'National Center for Mental Health crisis hotline.','url'=>'','available_hours'=>'24/7','languages'=>['Filipino','English']],
            // Mexico
            ['name'=>'SAPTEL','phone'=>'55 5259-8121','country'=>'Mexico','country_code'=>'MX','type'=>'helpline','description'=>'Emotional support and crisis intervention.','url'=>'https://www.saptel.org.mx','available_hours'=>'24/7','languages'=>['Spanish']],
        ];
        foreach ($resources as $r) CrisisResource::create($r);
    }

    private function seedResources()
    {
        $resources = [
            [
                'title'=>'4-7-8 Breathing Technique','description'=>'A simple breathing exercise to reduce anxiety and promote relaxation.','category'=>'anxiety','content_type'=>'breathing','tags'=>['breathing','anxiety','relaxation'],'icon'=>'🌬️','duration'=>'5 minutes','difficulty'=>'beginner',
                'body'=>"The 4-7-8 breathing technique, also known as \"relaxing breath,\" was developed by Dr. Andrew Weil. It acts as a natural tranquilizer for the nervous system.\n\nHow to Practice:\n\n1. Find a comfortable seated position and relax your shoulders.\n2. Place the tip of your tongue against the ridge behind your upper front teeth.\n3. Exhale completely through your mouth, making a whoosh sound.\n4. Close your mouth and inhale quietly through your nose for 4 seconds.\n5. Hold your breath for 7 seconds.\n6. Exhale completely through your mouth for 8 seconds, making a whoosh sound.\n7. This completes one cycle. Repeat 3-4 times.\n\nWhen to Use It:\n- Before sleep to combat insomnia\n- During moments of anxiety or panic\n- Before a stressful event (exam, presentation, difficult conversation)\n- Anytime you need to calm your nervous system\n\nTips for Success:\n- Practice twice daily for best results\n- Start with 4 cycles and gradually increase\n- If holding for 7 seconds is difficult, speed up but keep the 4:7:8 ratio\n- The exhale should always be twice as long as the inhale\n\nWhy It Works:\nThis technique forces your mind to focus on breathing rather than worries. The extended exhale activates your parasympathetic nervous system (your body's 'rest and digest' mode), lowering heart rate and blood pressure."
            ],
            [
                'title'=>'Progressive Muscle Relaxation','description'=>'Systematically tense and release muscle groups to reduce physical tension and stress.','category'=>'stress','content_type'=>'exercise','tags'=>['relaxation','stress','body'],'icon'=>'💪','duration'=>'15 minutes','difficulty'=>'beginner',
                'body'=>"Progressive Muscle Relaxation (PMR) was developed by Edmund Jacobson in the 1930s. It involves tensing and then releasing different muscle groups to achieve deep physical relaxation.\n\nStep-by-Step Guide:\n\n1. Find a quiet, comfortable place. Lie down or sit comfortably.\n2. Close your eyes and take 3 deep breaths.\n3. Start with your feet:\n   - Curl your toes tightly for 5 seconds\n   - Release and notice the relaxation for 10 seconds\n4. Move to your calves:\n   - Point your toes toward your shins for 5 seconds\n   - Release and relax for 10 seconds\n5. Continue upward through each muscle group:\n   - Thighs (press knees together)\n   - Stomach (tighten abdominal muscles)\n   - Chest (take a deep breath and hold)\n   - Hands (make tight fists)\n   - Arms (curl biceps)\n   - Shoulders (shrug toward ears)\n   - Face (scrunch all facial muscles)\n6. Finally, tense your entire body at once for 5 seconds, then release.\n\nKey Principles:\n- Never tense to the point of pain\n- Focus on the contrast between tension and relaxation\n- The relaxation phase is more important than the tension phase\n- Practice daily for cumulative benefits\n\nBenefits:\n- Reduces muscle tension and physical stress\n- Improves sleep quality\n- Lowers blood pressure\n- Decreases anxiety and panic symptoms\n- Helps with headaches and chronic pain"
            ],
            [
                'title'=>'Understanding Depression','description'=>'Learn about depression symptoms, causes, and evidence-based treatment options.','category'=>'depression','content_type'=>'article','tags'=>['depression','education','mental health'],'icon'=>'📖','duration'=>'8 min read','difficulty'=>'beginner',
                'body'=>"Depression is more than just feeling sad. It is a serious but treatable medical condition that affects how you feel, think, and handle daily activities.\n\nCommon Symptoms:\n- Persistent sad, anxious, or \"empty\" mood\n- Loss of interest in activities you once enjoyed\n- Changes in appetite or weight\n- Difficulty sleeping or oversleeping\n- Loss of energy or increased fatigue\n- Feelings of worthlessness or guilt\n- Difficulty concentrating or making decisions\n- Thoughts of death or suicide\n\nWhat Causes Depression:\nDepression has no single cause. It often results from a combination of:\n- Biological factors (brain chemistry, hormones, genetics)\n- Psychological factors (negative thinking patterns, trauma)\n- Environmental factors (stress, loss, isolation)\n\nEvidence-Based Treatments:\n\n1. Psychotherapy\n   - Cognitive Behavioral Therapy (CBT): Helps identify and change negative thought patterns\n   - Interpersonal Therapy (IPT): Focuses on improving relationships\n   - Behavioral Activation: Gradually re-engaging in meaningful activities\n\n2. Lifestyle Changes\n   - Regular exercise (30 minutes, 5 times a week)\n   - Consistent sleep schedule\n   - Balanced nutrition\n   - Social connection\n   - Limiting alcohol and avoiding drugs\n\n3. Professional Help\n   - Consult your primary care doctor\n   - See a licensed therapist or counselor\n   - Consider psychiatric evaluation if symptoms are severe\n\nRemember:\n- Depression is NOT a sign of weakness\n- Recovery is possible with the right support\n- Reaching out for help is a sign of strength\n- If you are in crisis, contact a helpline immediately"
            ],
            [
                'title'=>'Sleep Hygiene Guide','description'=>'Practical tips for improving your sleep quality and establishing a healthy bedtime routine.','category'=>'sleep','content_type'=>'article','tags'=>['sleep','habits','wellness'],'icon'=>'🌙','duration'=>'6 min read','difficulty'=>'beginner',
                'body'=>"Good sleep hygiene means having habits that help you get quality sleep consistently. Poor sleep affects mood, concentration, immunity, and mental health.\n\nThe Golden Rules of Sleep Hygiene:\n\n1. Stick to a Schedule\n   - Go to bed and wake up at the same time daily, even on weekends\n   - Your body's internal clock thrives on consistency\n\n2. Create a Sleep-Friendly Environment\n   - Keep your bedroom cool (18-20°C / 65-68°F)\n   - Make it dark: use blackout curtains or an eye mask\n   - Keep it quiet: use earplugs or a white noise machine\n   - Reserve your bed for sleep only (no work, no scrolling)\n\n3. Watch What You Consume\n   - Avoid caffeine after 2 PM\n   - Limit alcohol (it fragments sleep)\n   - Don't eat heavy meals within 2-3 hours of bedtime\n   - Stay hydrated but don't drink too much before bed\n\n4. Build a Wind-Down Routine (30-60 minutes before bed)\n   - Dim the lights\n   - Put away screens (blue light blocks melatonin)\n   - Try gentle stretching, reading, or a warm bath\n   - Practice relaxation techniques\n\n5. Daytime Habits That Improve Night Sleep\n   - Get natural sunlight within 1 hour of waking\n   - Exercise regularly (but not within 3 hours of bed)\n   - Limit naps to 20 minutes before 3 PM\n\nIf You Can't Fall Asleep:\n- Don't watch the clock\n- If you're awake for 20+ minutes, get up and do something calm\n- Return to bed only when you feel sleepy\n- Avoid screens during this time"
            ],
            [
                'title'=>'5-Minute Mindfulness Meditation','description'=>'A quick guided meditation to center yourself and reduce stress.','category'=>'meditation','content_type'=>'exercise','tags'=>['meditation','mindfulness','calm'],'icon'=>'🧘','duration'=>'5 minutes','difficulty'=>'beginner',
                'body'=>"This simple meditation can be done anywhere — at your desk, on a park bench, or in bed. All you need is 5 minutes.\n\nGuided Practice:\n\nMinute 1 — Arrive\n- Sit comfortably with your feet flat on the floor\n- Rest your hands on your lap\n- Gently close your eyes or soften your gaze\n- Take 3 deep breaths: in through the nose, out through the mouth\n\nMinute 2 — Notice Your Body\n- Scan from the top of your head to your toes\n- Notice any areas of tension without trying to change them\n- Let your breathing return to its natural rhythm\n\nMinute 3 — Follow Your Breath\n- Focus your attention on the sensation of breathing\n- Notice the air entering your nostrils, your chest rising, your belly expanding\n- When your mind wanders (and it will), gently bring attention back to your breath\n- No judgment — wandering minds are completely normal\n\nMinute 4 — Expand Awareness\n- While maintaining awareness of your breath, expand attention outward\n- Notice sounds around you without labeling them as good or bad\n- Notice the temperature of the air on your skin\n- Simply observe without reacting\n\nMinute 5 — Return\n- Bring your attention back to your body sitting in the chair\n- Wiggle your fingers and toes\n- Take one final deep breath\n- Open your eyes slowly\n\nTips:\n- Set a gentle timer so you don't worry about time\n- Don't aim for a \"blank mind\" — that's a myth\n- Consistency matters more than duration\n- Try to practice at the same time each day"
            ],
            [
                'title'=>'Managing Exam Stress','description'=>'Strategies for students to cope with academic pressure and perform their best.','category'=>'stress','content_type'=>'article','tags'=>['students','exams','stress'],'icon'=>'📚','duration'=>'7 min read','difficulty'=>'beginner',
                'body'=>"Exam stress is one of the most common challenges students face. Some stress is normal and can even help performance, but too much can be paralyzing.\n\nBefore Exams — Preparation Strategies:\n\n1. Plan Your Study Schedule\n   - Break material into manageable chunks\n   - Use spaced repetition (study over multiple days, not all at once)\n   - Prioritize topics by difficulty and importance\n   - Include breaks every 25-50 minutes (Pomodoro Technique)\n\n2. Active Study Methods\n   - Teach concepts to someone else (or explain aloud to yourself)\n   - Create mind maps and visual summaries\n   - Practice with past papers under timed conditions\n   - Use flashcards for key terms and concepts\n\n3. Take Care of Your Body\n   - Sleep 7-9 hours (sleep consolidates memory)\n   - Eat regular, balanced meals\n   - Exercise daily, even if just a 20-minute walk\n   - Stay hydrated\n\nDuring Exams — Performance Tips:\n\n1. Read all questions before starting\n2. Start with questions you feel most confident about\n3. If you feel panicked, use box breathing (4-4-4-4)\n4. Don't compare your progress with others\n5. If you go blank, skip and return later\n\nAfter Exams — Recovery:\n- Avoid post-mortems with classmates\n- Do something enjoyable and relaxing\n- Remember: one exam does not define your worth\n- If stress persists, talk to a counselor\n\nRemember:\n- Perfection is not the goal — doing your best is enough\n- Struggling does not mean you are not smart enough\n- It is okay to ask for help or extensions when overwhelmed"
            ],
            [
                'title'=>'Box Breathing Exercise','description'=>'A calming technique used by Navy SEALs: breathe in, hold, out, hold — each for 4 seconds.','category'=>'anxiety','content_type'=>'breathing','tags'=>['breathing','focus','calm'],'icon'=>'📦','duration'=>'4 minutes','difficulty'=>'beginner',
                'body'=>"Box breathing (also called square breathing) is used by Navy SEALs, athletes, and first responders to stay calm under extreme pressure. It's simple, effective, and can be done anywhere.\n\nHow to Practice:\n\n1. Sit upright in a comfortable position\n2. Slowly exhale all the air from your lungs\n3. Breathe IN through your nose for 4 seconds\n4. HOLD your breath for 4 seconds\n5. Breathe OUT through your mouth for 4 seconds\n6. HOLD (lungs empty) for 4 seconds\n7. Repeat for 4-5 cycles\n\nVisualize a Box:\nImagine tracing a square as you breathe:\n- Left side going up = Inhale (4 seconds)\n- Top side going right = Hold (4 seconds)\n- Right side going down = Exhale (4 seconds)\n- Bottom side going left = Hold (4 seconds)\n\nWhen to Use Box Breathing:\n- Before a stressful meeting or presentation\n- When anxiety begins to build\n- During or after an argument\n- Before making an important decision\n- When you need to regain focus\n- Before sleep\n\nWhy It Works:\n- Activates the parasympathetic nervous system\n- Lowers cortisol (stress hormone) levels\n- Improves focus and mental clarity\n- Regulates the autonomic nervous system\n\nAdvanced Variation:\nOnce comfortable with 4 seconds, try increasing to 5 or 6 seconds per phase. The longer the cycle, the deeper the relaxation response."
            ],
            [
                'title'=>'Recognizing Burnout','description'=>'How to identify the signs of burnout before it becomes overwhelming.','category'=>'burnout','content_type'=>'article','tags'=>['burnout','work','self-care'],'icon'=>'🔥','duration'=>'6 min read','difficulty'=>'beginner',
                'body'=>"Burnout is not just being tired — it is a state of chronic physical and emotional exhaustion caused by prolonged stress. Recognizing it early is crucial for recovery.\n\nThe Three Dimensions of Burnout:\n\n1. Exhaustion\n   - Feeling drained physically and emotionally\n   - Difficulty getting out of bed\n   - Constant fatigue that rest does not fix\n\n2. Cynicism / Detachment\n   - Feeling disconnected from your work or relationships\n   - Increased irritability and negativity\n   - Loss of purpose or meaning\n\n3. Reduced Effectiveness\n   - Decreased productivity despite working harder\n   - Difficulty concentrating\n   - Feeling incompetent or like a failure\n\nEarly Warning Signs:\n- Dreading work or responsibilities\n- Withdrawing from social interactions\n- Neglecting personal needs (sleep, exercise, nutrition)\n- Physical symptoms (headaches, stomach issues, frequent illness)\n- Using substances to cope\n- Feeling trapped or hopeless\n\nRecovery Strategies:\n\n1. Set Boundaries\n   - Learn to say no to additional commitments\n   - Set work hours and stick to them\n   - Turn off work notifications after hours\n\n2. Prioritize Recovery\n   - Schedule non-negotiable rest time\n   - Engage in activities that recharge you\n   - Take actual breaks (not working through lunch)\n\n3. Seek Support\n   - Talk to your manager about workload\n   - Connect with supportive friends and family\n   - Consider professional counseling\n\n4. Reassess\n   - Evaluate your values and whether your current path aligns\n   - Consider what changes are within your control\n   - Small changes can make a significant difference"
            ],
            [
                'title'=>'Gratitude Journaling Guide','description'=>'How keeping a gratitude journal can improve your mental health and overall wellbeing.','category'=>'meditation','content_type'=>'article','tags'=>['gratitude','journaling','positivity'],'icon'=>'📝','duration'=>'5 min read','difficulty'=>'beginner',
                'body'=>"Research shows that regularly practicing gratitude can increase happiness by 25%, improve sleep quality, and reduce symptoms of depression.\n\nHow to Start a Gratitude Journal:\n\n1. Choose Your Format\n   - A physical notebook (many people find handwriting more impactful)\n   - A digital journal or app (like the journal feature on this platform)\n   - Even a simple notes app on your phone\n\n2. Set a Daily Time\n   - Morning: Sets a positive tone for the day\n   - Evening: Helps you reflect and sleep better\n   - Pick one time and be consistent\n\n3. The Practice (5 minutes)\n   - Write down 3-5 things you are grateful for\n   - Be specific (not just \"family\" but \"my sister's encouraging text this morning\")\n   - Include small things (a good cup of coffee, sunshine, a stranger's smile)\n   - Try to find new things each day\n\nPrompts to Get Started:\n- What made me smile today?\n- Who am I grateful for and why?\n- What is something I often take for granted?\n- What challenge taught me something valuable?\n- What simple pleasure did I enjoy today?\n\nDeepening Your Practice:\n- Write why each item matters to you\n- Include at least one thing about yourself you appreciate\n- Revisit past entries when you are feeling low\n- Share your gratitude with others\n\nThe Science:\n- Gratitude activates the brain's reward system\n- It reduces the stress hormone cortisol by 23%\n- Regular practice physically changes brain structure over time\n- It builds resilience against depression and anxiety"
            ],
            [
                'title'=>'Body Scan Meditation','description'=>'A guided body scan to release tension and increase body awareness.','category'=>'meditation','content_type'=>'exercise','tags'=>['meditation','body','relaxation'],'icon'=>'🧘','duration'=>'10 minutes','difficulty'=>'beginner',
                'body'=>"A body scan meditation systematically brings awareness to every part of your body, helping release stored tension and promoting deep relaxation.\n\nPreparation:\n- Lie down on your back on a comfortable surface\n- Arms resting at your sides, palms up\n- Close your eyes\n- Take 3 deep breaths\n\nThe Practice:\n\n1. Feet (1 minute)\n   Bring attention to the soles of your feet. Notice any sensations — warmth, tingling, pressure. Breathe into this area and release.\n\n2. Legs (1.5 minutes)\n   Move awareness up through your ankles, calves, knees, and thighs. Notice any tightness. With each exhale, imagine tension melting away.\n\n3. Pelvis and Lower Back (1 minute)\n   Notice the weight of your hips against the surface. Breathe into your lower back, a common area for stored stress.\n\n4. Abdomen and Chest (1.5 minutes)\n   Feel your belly rising and falling with each breath. Notice your heartbeat. Allow your chest to soften with each exhale.\n\n5. Hands and Arms (1 minute)\n   Bring awareness to your fingertips, palms, wrists, forearms, and upper arms. Let any tension dissolve.\n\n6. Shoulders and Neck (1.5 minutes)\n   These hold the most tension for many people. Breathe deeply into your shoulders. With each exhale, let them drop away from your ears.\n\n7. Face and Head (1.5 minutes)\n   Soften your jaw. Unclench your teeth. Relax your forehead, the muscles around your eyes, and your scalp.\n\n8. Whole Body (1 minute)\n   Expand awareness to your entire body at once. Feel yourself as one unified whole, relaxed and present. Rest here for a few breaths.\n\nClosing:\n   Gently wiggle your fingers and toes. Take a deep breath. Open your eyes slowly when you are ready."
            ],
            [
                'title'=>'Healthy Relationship Boundaries','description'=>'Learn to set and maintain healthy boundaries in your relationships.','category'=>'relationships','content_type'=>'article','tags'=>['relationships','boundaries','communication'],'icon'=>'💛','duration'=>'7 min read','difficulty'=>'intermediate',
                'body'=>"Boundaries are the limits we set in relationships that allow us to protect our wellbeing while maintaining healthy connections with others.\n\nTypes of Boundaries:\n\n1. Physical Boundaries\n   - Personal space and touch preferences\n   - Privacy needs\n   - Physical needs (sleep, food, rest)\n\n2. Emotional Boundaries\n   - Separating your feelings from others'\n   - Not taking responsibility for others' emotions\n   - Protecting yourself from emotional manipulation\n\n3. Time Boundaries\n   - How you spend your time\n   - Saying no to commitments that drain you\n   - Protecting time for self-care\n\n4. Digital Boundaries\n   - Response time expectations\n   - Social media sharing limits\n   - Privacy online\n\nHow to Set Boundaries:\n\n1. Identify Your Needs\n   - What makes you feel uncomfortable or resentful?\n   - What do you need to feel safe and respected?\n\n2. Communicate Clearly\n   - Use \"I\" statements: \"I need...\" instead of \"You always...\"\n   - Be specific: \"I need 30 minutes alone after work\" vs. \"I need space\"\n   - Be firm but kind\n\n3. Follow Through\n   - Boundaries without consequences are just suggestions\n   - State what you will do if the boundary is crossed\n   - Actually follow through\n\n4. Handle Pushback\n   - Some people will resist your new boundaries\n   - This does not mean your boundary is wrong\n   - Repeat calmly: \"I understand, but this is what I need\"\n\nSigns of Unhealthy Boundaries:\n- Saying yes when you want to say no\n- Feeling responsible for others' happiness\n- Allowing others to define your feelings\n- Giving more than you can afford (time, energy, money)\n- Tolerating disrespect or abuse\n\nRemember: Setting boundaries is not selfish — it is self-care."
            ],
            [
                'title'=>'Work-Life Balance Tips','description'=>'Practical strategies for maintaining balance between professional and personal life.','category'=>'burnout','content_type'=>'article','tags'=>['work','balance','wellness'],'icon'=>'⚖️','duration'=>'6 min read','difficulty'=>'intermediate',
                'body'=>"Work-life balance does not mean perfect 50/50 — it means creating a sustainable rhythm where both work and personal life receive adequate attention.\n\nStrategies That Actually Work:\n\n1. Define Your Non-Negotiables\n   - Identify 3-5 activities that are essential for your wellbeing\n   - Schedule them like important meetings\n   - Examples: family dinner, exercise, 8 hours of sleep, a hobby\n\n2. Set Work Boundaries\n   - Define clear start and end times for work\n   - Create a shutdown ritual (close laptop, change clothes, take a walk)\n   - Turn off work notifications outside work hours\n   - If working from home, have a dedicated workspace\n\n3. Learn to Prioritize\n   - Use the Eisenhower Matrix: Urgent/Important vs. Not Urgent/Not Important\n   - Accept that not everything can be done perfectly\n   - Delegate when possible\n   - Say no to things that do not align with your priorities\n\n4. Protect Your Energy\n   - Identify your peak productivity hours and do deep work then\n   - Batch similar tasks together\n   - Take real breaks (step away from screens)\n   - Schedule buffer time between meetings\n\n5. Invest in Recovery\n   - Weekends should include genuine rest, not just a different kind of work\n   - Plan vacations and take them without guilt\n   - Have at least one screen-free hour daily\n   - Engage in hobbies that have nothing to do with work\n\n6. Address the Root Causes\n   - If your workload is unsustainable, have an honest conversation with your manager\n   - If perfectionism drives overwork, consider therapy\n   - If financial fears keep you working excessively, create a financial plan\n\nSigns You Need to Rebalance:\n- Relationships are suffering\n- You feel guilty when not working\n- Physical health is declining\n- You cannot remember the last time you truly relaxed\n- You have lost interest in things you used to enjoy"
            ],
        ];
        foreach ($resources as $r) Resource::create($r);
    }
}

